language: php

php:
  - '7.0'
  - '7.1'
  - nightly

matrix:
  fast_finish: true
  include:
    - php: '7.0'
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - find src spec -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - phpdbg -qrr vendor/bin/phpspec run
