language: php

cache:
  directories:
  - $HOME/.composer/cache/

php:
  - '7.0'
  - '7.1'
  - nightly

matrix:
  allow_failures:
    - php: '7.1'
    - php: nightly
  fast_finish: true
  include:
    - php: '7.0'
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - find src spec -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - composer validate
  - phpdbg -qrr vendor/bin/phpspec run

after_success:
  - travis_retry php vendor/bin/coveralls
